extensions:
  health_check:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

processors:
  batch:

exporters:
  otlp/elastic:
    endpoint: {{ Elastic APM URL }}
    headers:
      Authorization: "Bearer {{ Elastic APM Secret Token }}"
  logging:
    loglevel: debug

service:
  extensions: [health_check, memory_ballast, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]

