== Manual Instrumentation

=== Introduction

This repository holds the demo asset in enabling distributed tracing for Kafka Client program using standard OpenTelemetry manual instrumentation through SDK auto-configuration.

You need to include the following Maven dependencies in your Kafka program.

Maven

====
----
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>1.24.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom-alpha</artifactId>
        <version>1.24.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-otlp</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk-extension-autoconfigure</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry.instrumentation</groupId>
      <artifactId>opentelemetry-kafka-clients-2.6</artifactId>
      <version>1.24.0-alpha</version>
    </dependency>
    ...
  </dependencies>
----
====

Gradle

====
----

dependencies {
    implementation 'io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.24.0'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp:1.24.0'
    implementation 'io.opentelemetry:opentelemetry-kafka-clients-2.6:1.24.0-alpha'
}

----
====



OpenTelemetry documentation and sources - https://opentelemetry.io/[main site], https://github.com/open-telemetry[github]



=== Before running the demo

Modify energy-generator/src/main/resources/producer.properties according to your Confluent Cloud environment

----
bootstrap.servers={{ BOOTSTRAP_SERVERS }}
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='{{ CLUSTER_API_KEY }}' password='{{ CLUSTER_API_SECRET }}';
sasl.mechanism=PLAIN
acks=all
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.IntegerSerializer
client.id=EnergyGenerator
topic=energy-topic
----


Modify energy-reader/src/main/resources/consumer.properties according to your Confluent Cloud environment

----
bootstrap.servers={{ BOOTSTRAP_SERVERS }}
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='{{ CLUSTER_API_KEY }}' password='{{ CLUSTER_API_SECRET }}';
sasl.mechanism=PLAIN
acks=all
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.IntegerSerializer
max.poll.interval.ms=300000
enable.auto.commit=true
auto.offset.reset=earliest
group.id=energy-readers
client.id=EnergyReader
topic=energy-topic
----

Create a Kafka Topic
----
confluent kafka topic create energy-topic --partitions 1
----


Start the OpenTelemetry Collector

----
cd kafka-tracing/collector/jaeger
docker-compose up -d
----


Browse to http://localhost:16686/[Jaeger UI]


Run energy-generator Kafka client program
----
cd energy-generator
mvn clean package

export OTEL_SERVICE_NAME=WindGenerator
export OTEL_TRACES_EXPORTER=otlp
export OTEL_METRICS_EXPORTER=none
export OTEL_LOGS_EXPORTER=none
java -Dotel.java.global-autoconfigure.enabled=true \
-jar ./target/EnergyGenerator-jar-with-dependencies.jar
----


Run energy-reader Kafka client program
----
cd energy-reader
mvn clean package

export OTEL_SERVICE_NAME=WindReader
export OTEL_TRACES_EXPORTER=otlp
export OTEL_METRICS_EXPORTER=none
export OTEL_LOGS_EXPORTER=none
java -Dotel.java.global-autoconfigure.enabled=true \
-jar ./target/EnergyReader-jar-with-dependencies.jar
----


=== Sample Telemetry in JaegerUI

*TBA*


=== Compatible OpenTelemetry versions

Both development of extension and installation requires compatible version of main OpenTelemetry Java Instrumentation.

Current build is targeting v1.13.0 of OpenTelemetry instrumentation.
